workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -138,6 +138,7 @@ jobs:
             echo "DOMAIN_BACK_URL: $DOMAIN_BACK_URL"
             cd backend
             FRONT_URL=$FRONT_URL DOMAIN_BACK_URL=$DOMAIN_BACK_URL python manage.py test tests.e2e.test_system
+          continue-on-error: true
 
         # - name: Run tests
         #   env:
@@ -153,10 +154,17 @@ jobs:
         #     docker compose up --abort-on-container-exit
 
         - name: Upload reports
+          if: always()
           uses: actions/upload-artifact@v4
           with:
             name: reports
             path: backend/reports
+
+        - name: Fail the job if tests failed
+          if: failure()  # Só executa se o passo anterior falhou
+          run: |
+            echo "Tests failed. See the report for details."
+            exit 1
 
 
 # $(hostname -I | awk '{print $1}')
